---
title: "iRain app for real-time rainfall observations from satellites and crowdsourcing"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

iRain provides access to real-time global high-resolution (~4km) satellite precipitation products from the PERSIANN-CCS (Precipitation Estimation from Remotely Sensed Information using the Artificial Neural Networks - Cloud Classification System), which has been developed by the research team at CHRS. The building block of iRain rests on the satellite precipitation estimates generated by the PERSIANN algorithm which has been under development for over two decades. More detailed information about PERSIANN-CCS can be found at http://chrs.web.uci.edu. 
 iRain allows users to visualize real-time global satellite precipitation observations and track extreme precipitation events globally. It is especially useful for monitoring extreme events related to atmospheric rivers affecting California. Users can also use the crowdsourcing functionality of the app to report their local rainfall information to supplement our data.

### Additional Resources

- [Slides](https://drive.google.com/file/d/0B_SI-qUI02kYZ0YwZzJnMU1Bdk0/view?usp=sharing)
- <https://itunes.apple.com/sa/app/irain-app/id982858283?mt=8>
- <http://irain.eng.uci.edu/>
- <http://en.unesco.org/news/irain-new-mobile-app-promote-citizen-science-and-support-water-management>
