---
title: "CASGEM Data Mining and Visualization Tools and Technologies for SMART WELLFIELDS™"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

Problem Statements• Groundwater Science is a “black box” to most people, because we cannot “see” under the ground. • The general public, ranchers, growers, regulators, and public and private water utilities cannot be expected to understand groundwater flow dynamics and well hydraulics. • The United States has a limited ability to use groundwater science for aquifer resource management because, while we have some excellent groundwater level data, we generally do not have pumping data that are contemporaneous. Hydrogeology can be very quantitative if you know the water level and corresponding pumping rate. Solutions StatementOur firms have been developing groundwater science hardware and software tools for over 20 years. We are not software companies – we are hydrogeologists who had a vision of better science through computing. The Internet of Things (IoT) is changing people’s perspective on what is possible. We have invented a turn-key process to collect and store large, continuous data sets (AQUIMETRICS™). We have developed algorithms to use either historic data or real-time/continuous data feeds to create groundwater contour maps on-the-fly and to assess well hydraulics (AQUILYTICS™). Using our telemetry (AQUIMETRICS™), Geographic Information System (GIS), database (EPIPHINY®), and coding technologies (AQUILYTICS™), we can visualize the quantity of groundwater, where it is coming from, where it is going, and how to optimize groundwater pumping to meet an objective. Wellfield operators also know how to save water, save electricity, and save maintenance costs on their wells. Our vision is to facilitate SMART WELLFIELDS™ - a network of wells where flow rate and water level information are continually analyzed to automatically turn pumps up and down (and on and off) to better manage an aquifer resource.Entry StatementLocational data and groundwater level data for the last 10 years obtained from CASGEM were easily imported into our EPIPHINY® platform for instantaneous analysis and to export to ArcGIS®, ArcScene®, and to link with our AQUILYTICS™ platform. Data trends and groundwater contour maps are easy to prepare for “snapshot” or time series analysis. With relatively little effort, our tools could be customized to become open source on behalf of any state and provide groundwater scientists, state and county employees, wellfield operators, and the general public sophisticated groundwater software tools. We are prepared to perform a demonstration project using all of our technologies and patent to create California’s first SMART WELLFIELDS™.

### Additional Resources

- [Slides](https://drive.google.com/open?id=0B5n4IeHrVBinVlhwSkVWZ1l1Ukk)
- <www.epiphiny.com>
- <www.realgw.com>
