---
title: "Coping with the California Drought: 2014-2016"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "Patricia Gonzales"
  - "Kim Quesnel"
  - "Newsha Ajami"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

Our submission contains interactive visualizations that allow the user to explore how effectively California water utilities conserved water over the past 3 years, a critical period of historical drought. By visualizing and exploring the relationships between water conservation in 2014, 2015, and 2016 in almost 400 utilities from around the state, we provide an interesting perspective of the ongoing drought. For these visualizations, we define "conservation" and "water savings" as the difference in water production between a timeframe of interest in a given supplier's service area and its respective water production in 2013. This exploratory analysis includes statewide data to show overall water use trends, as well as data for each of the 10 hydrologic regions in California and individual utilities in those regions. The comparison between conservation efforts in 2014, 2015, and 2016 also provides insight on the responsiveness of different utilities to different incentives: a voluntary call for conservation in 2014, a state mandate in 2015, and the replacement of the state mandate by adjusted self-certified goals in 2016.
 Several key lessons can be drawn from these visualizations: (1) The reporting requirements put in place during the drought created an even platform for water utilities to keep track of important data, which in turn allows tools like this one to identify water use and conservation trends, drivers, and opportunities for enhanced water management at a variety of different scales. Further standardized tracking and reporting methods could facilitate the use of data for decision-making; (2) Water utilities collectively achieved significant water savings in the period between 2014 and 2016. While policies and regulations seem to have been significant drivers of water conservation throughout the state (e.g. higher water savings during the state mandate or in response to local watering restrictions), these visualizations show that water use and conservation are very site-dependent and utility-specific; (3) Many uncertainties remain about the human-water dynamics that made water savings possible between 2014 and 2016. A better understanding of local population behaviors towards water use, and responsiveness to different conservation incentives, could help water planners and managers tailor their conservation campaigns more effectively in the future, not only during drought, but also as a long-term water reliability strategy.

### Additional Resources

- [Slides](https://drive.google.com/open?id=0B5n4IeHrVBinT3NlRndpam85Y2c)
- <http://waterinthewest.stanford.edu/publications/coping-california-drought-2014-2016>
- <https://github.com/patriciagm4/ca-data-challenge >
