---
title: "Sustainable Floodplain Habitat Finder"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

Chinook salmon in California's Central Valley are struggling to survive. During their epic migration from the ocean into the tributary streams draining the Central Valley, salmon contend with depleted streamflows, migration barriers, predators, degraded habitat, lack of nutrients, and a host of other challenges. Baby salmon are especially vulnerable during their long migration from the spawning grounds downstream to the ocean. Additional floodplain habitat may be the key to restoring dwindling salmon populations; by providing food, cover from predators; and higher rates of survival. But - restoring floodplain habitat requires a careful balance of current and future streamflow conditions, groundwater basin conditions, and, of course, baby salmon migration patterns.
 
 Our entry is an open source combination of data visualization and decision support tools for water resources and fishery managers who must constantly make difficult decisions about how to allocate streamflows to meet a wide range of human and ecosystem needs. Our tool is an R Shiny application that incorporates the Leaflet map service, Plotly charting tools, the National Oceanic and Atmospheric Administration River Forecast web service, and R-based statistical evaluation interfaces to evaluate, in a real-time data-driven way, the relative potential for floodplain habitat creation at a given site.

### Additional Resources

- [Slides](https://drive.google.com/file/d/0B5n4IeHrVBinY1JIOFlxUkNXajQ/view?resourcekey=0-qQlutJZZ07waa9rqy1hPHQ)
- <https://flowwest.shinyapps.io/flowwest_floodplain_habitat_finder/>
