---
title: "An Automated Water Resources Tracking System: Near Real-Time Decision Support for Water and Wetland Managers"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

Competition for water is likely to intensify as California is projected to experience continued increases in demand due to population growth, more arid growing conditions, and reduced or modified water supply due to climate change. As water resources become increasingly limited, water use needs to be optimized across many competing demands while also promoting multiple-benefits. Though sophisticated water optimization models can be useful for tracking water volume allocations, how the results translate into habitat availability for wildlife and ecosystem services for people is not known. A framework is needed to better understand the spatial distribution of water in near real-time for managers to adapt to changing conditions on the landscape and to maximize the value of the water used.
 
 We are integrating remote sensing of satellite data, classification modeling, bioinformatics, optimization, and ecological analyses to develop an automated near real-time water resources tracking and decision-support system for the Central Valley of California. The system provides information on open surface water every 16-days and delineates between wetland types and flooded agriculture. Data are made freely available online for download 3-6 days post acquisition as well as through online summary and map visualization applications. Data are also summarized specifically for wetland wildlife habitats within federal and state management areas. These data will be used by water and wetland managers to enhance landscape scale coordination of limited water supplies for wildlife, particularly during drought. In our complete vision for this system, water managers will be able to get near-real time and forecasted recommendations for where to put water on the landscape to achieve multiple wildlife habitat targets but to also provide ecosystem services (e.g. groundwater recharge). 
 
 Our innovative system has applications for water management in the Central Valley to support people, places, and wildlife and is already being used for understanding the factors that drive variation in the distribution and abundance of water resources at multiple spatial and temporal scales. Specifically data generated as part of this system are being applied to assess the impact of the most recent drought in California, to understand the effect of disease vector control on water distribution, to quantify the groundwater recharge potential of current surface water management for wildlife, to develop an avian influenza risk map, and to identify where to put water and when on agricultural lands to benefit migratory birds.

### Additional Resources

- [Slides](https://drive.google.com/file/d/0B5n4IeHrVBinWnN2eWVHM1g4aFE/view?resourcekey=0-HcUn236odEPuW98wyUUuyQ)
- <http://data.pointblue.org/apps/autowater/>
- <https://github.com/dm00dy/autowater>
