---
title: "Sacramento River Watershed Data Portal"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

The Sacramento River is the largest river and watershed system in California. This 27,000-square mile basin drains the eastern slope of Shasta, the western slopes of the Cascades and the northern portion of the Sierra Nevada and runs 31% of the state’s total surface runoff. The Sacramento River Basin provides drinking water for millions, supplies farmers with water for California’s agriculture and is the lifeblood for hundreds of wildlife species including four runs of Chinook salmon. 
 
 To help successfully manage this dynamic and diverse system, 34 North was tasked with a major data aggregation and software development effort in order to help inform stakeholders with accurate and timely information. The SRWP data platform is used for key management issues including:
 
 ü Collaborative resource management
 ü Salmon/steelhead passage and habitat
 ü Wild trout/native fish
 ü Forest health/fuels management
 ü Aquatic and riparian habitat
 ü Water quality
 ü Water supply
 ü Flood management
 ü Open space and land conservation
 ü Erosion and natural stream function
 ü Invasive species
 ü Temperature management

### Additional Resources

- [Slides](https://drive.google.com/open?id=0B5n4IeHrVBinWXFVdjctTW5DNTQ)
- <srwp.opennrm.org>
 username: guest@srwp.org
 password: srwp
