---
title: "Smart Water Analytics"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

Smart Water Analytics is the industry leading innovative & advanced technology solution leveraging some of open sources software combined with Accenture’s knowledge and experience in the water industry. Smart Water solution is not only helping States, Cities, Municipalities & counties in North America but also some of the leading water supplier across the globe in water conservation and to provide safe drinking water 
 
 Our solution focuses on Ground Water and some of the salient features are mentioned below:
 Technology: -Built on Cloud technology & leveraging some of the open software like Hadoop, Spark, Scoop, MySQL -Provides Analytics capabilities to look at data either in Dashboard or Map form -Leveraged “R” programing language to do comparison analysis of two or more counties for chemicals usage and number of wellsBusiness- Demonstrates capability to get answers to three (3) use cases in a very intuitive manner -Use Case 1 : Analyze trends of specific chemicals used in wells across the state level and deep dive at the well level -Use Case 2: Counties wherein the number of wells has increased -Use Case 3 : Attributing the increase in wells to increase in population or weather condition

### Additional Resources

- [Slides](https://drive.google.com/open?id=0B5n4IeHrVBinZ2NPX0JWQ0IxX2s)
- <https://accenture-smartwateranalytics.ca-challenge.com> Note: This website is not publically accessible, hence please send request to following email address to get access Sachin.dalal@accenture.com & sonu.kumar.singh@accenture.com
