---
title: "EMP Water Quality Conditions Report (Water Quality Conditions in the Sacramento San Joaquin Bay-Delta and Suisun Bay)"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description:

The Bay-Delta Monitoring and Analysis Section within DWR’s Division of Environmental Services is part of the Environmental Monitoring Program (EMP) that monitors water quality, benthic macro invertebrates, and phytoplankton at discrete stations in the Sacramento-San Joaquin Delta, Suisun Bay, and San Pablo Bay. The monitoring conducted by the EMP is mandated by State Water Resources Control Board (SWRCB) - Water Rights Decision 1641 for operation of the State Water Project. The EMP program was established in 1970 and static “hardcopy” Water Quality Conditions reports have been published containing data from 1970 to 2011. This project, developed by 34 North was initiated to make the mandated data more accessible and usable in a web-based Interactive Water Quality Conditions Report Portal. 
 
 The SWRCB’s D-1641 mandates DWR to: 1) conduct a comprehensive environmental monitoring program to determine DWR’s compliance with water quality standards and 2) annually report on the data collected. Development of a web-based Interactive Water Quality Conditions Report was initiated by DWR and the State and Federal Water Contractors (SWFCA), as part of the SWRCB “My Water Quality Portals”. This new web-based report intends to replace the publication of the hard-copy version of the WQC report and will improve compliance requirements for the D-1641 Monitoring Report. DWR’s last WQC report for 2011 was published in 2012 and this new format will provide the following improvements:
 • Real time reporting and updates available to the public in an easy to use web interface.
 • Reduce staff time required to develop these reports and allow more time for data analysis and problem solving. 
 • Make all EMP data available and useful for scientists and managers to respond to recent court decisions, biological opinions, and mandates for drought responses.
 • Trend analysis.
 • Program data will be made available via web services for other water quality programs and scientific efforts.

### Additional Resources

- [Slides](https://drive.google.com/open?id=0B5n4IeHrVBinQVVXWFUtSlZteDA)
- <http://mywaterquality.ca.gov/index.html>
