---
title: "Aggregating Municipal and State Open Data for Water Quality Investigations"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "Eric Bollens"
  - "Jason Locklin"
  - "Jonny Sandu"
  - "Justin Grewal"
  - "Amanda Iaali"
  - "Kelvin Liu"
  - "Bryan Pastor"
  - "Grant Sharp"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 Data Innovation Challenge"
  - "Overall Winner 🏆"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

Water quality monitoring required by municipal separate storm sewer system (MS4) permits in California generally focuses on determining the status and trends of conditions in receiving waters as they relate to designated beneficial uses. Results provide a pulse for the watershed. Just like a human pulse, while this information highlights if an issue exists, using it to find the source of the stressor is much more complex. 

This study presents a method for aggregating state and municipal data sources to assist with source identification. Specifically, it uses open data from Orange County Public Works (OCPW) and the California Storm Water Multiple Action and Report Tracking System (SMARTS) to identify possible dischargers responsible for exceedances of user-defined thresholds within Orange County’s watersheds. While applied to historical data because of the lack of real-time data sources, the application of this method with real-time sources enables quick reaction to degradations in water quality.

### Additional Resources

- [Paper: Aggregating Municipal And State Open Data For Water Quality Investigations.Pdf](http://wqexplorer.cloudcompli.com/paper#)
- [Application: Wqexplorer (Select Either “Ctr Limits” Or “Deviation” From The Menu To Start An Investigation)](http://wqexplorer.cloudcompli.com/#)
- [Source Code (For Web Application): Https://Github.Com/Cloudcompli/Wqexplorer](https://github.com/cloudcompli/wqexplorer#)
- [Source Code (For An Underlying Data Parsing Library): Https://Github.Com/Cloudcompli/Wqinspector](https://github.com/cloudcompli/wqinspector#)
- [Presentation: Aggregating Municipal And State Open Data For Water Quality Investigations](http://www.waterboards.ca.gov/resources/data_databases/docs/aggregatingdata_pres.mp4#)
- [Slides: Aggregating Municipal And State Open Data For Water Quality Investigations](http://www.waterboards.ca.gov/resources/data_databases/docs/aggregatingdata.pdf#)
