---
title: "CaDC Gittes Water Data Dictionary and Explorer"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
  - "Honorable Mention 🏆"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

Charles Fishman, in a New York Times op-ed commented that “Water is Broken. Data can Fix it” made the case that analytics and systems borrowed from the technology industry can come to the aid to water conservation efforts. Many others including the California Council of Science and Technology, the Western Governors Association, and the Delta Stewardship Council have called for improvements in our water data systems. 
 
 AB 1755 or The Open and Transparent Water Data Act is recent California legislation calls for the development of an Integrated water data platform to “help water managers operate California’s water system more effectively and help water users make informed decisions based on water availability and allocation”. In addition to catering to the water manager community, the Dodd bill also calls for the intended water data platform to “promote openness and interoperability of water data by making information accessible, discoverable, and usable by the public to foster entrepreneurship, innovation, and scientific discovery.”
 
 These are indeed lofty policy goals that require a coalition of the willing to come together, build common ground and work towards the future of water management California needs. In short there is a key need to develop tools to create and sustain shared understanding amongst various stakeholders. 
 
 The GITTES Water Data Dictionary and Water Data explorer is a bottom-up effort that attempts to cater to these needs and ensure that the focus of any digital effort is on the delivery of the vision laid out in AB 1755. To that end, this submission is a first step towards creating “protocols for data sharing, documentation, quality control, public access, and promotion of open-source platforms and decision support tools related to water data.”
 
 The Water Data Dictionary is a simple cataloging effort that carefully indexes all relevant water data sources into a single schema. It was developed keep agile development methodology in mind and continuously iterating towards continuous improvement. 
 
 Image: Methodology
 
 We adopt a concept called the Common Operational Picture to develop the Water Data explorer, a data visualization that is powered by the Water Data dictionary. The Common Operational Picture or COP is grounded in years of decision-science research as being a best-practice and effective tool often used in crisis and emergency management settings. The COP facilitates continuous situational awareness through the management of disparate and heterogeneous data to across the various that stakeholders, end-users and end-beneficiaries.
  
 Image: A Common operational picture visualization for CA Water Data
 
 We believe that the combination of the data practices, co-creation efforts, decision-making, and co-creation which have been put into practice here are enablers to fully realize and sustain the Integrated Water Data Platform that is called for in the Dodd Bill. This initial project uses Tableau technology so is not open source. It falls under the decision support category.

### Additional Resources

- [Slides](NA)
- <http://public.tableau.com/views/GITTES-viz/Dashboard2?:showVizHome=no#1>
- <https://drive.google.com/open?id=0B5n4IeHrVBinN19LbklYa0NRaUU>
