---
title: "CA H2Open"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "Andrew Holguin"
  - "Yoni Ackerman"
  - "Frank Loge"
  - "Edward Spang"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 Data Innovation Challenge"
  - "Runner-Up 🏆"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

In April 2015, Governor Brown mandated a 25 percent statewide reduction in water use by urban water suppliers across the state (relative to 2013 levels) with differentiated conservation targets for utilities with varying levels of baseline per capita usage (Executive Order B-29-15). The more than 400 public water agencies affected by the regulation were also required to report monthly progress towards the conservation goal to the State Water Board. This application uses the reported data to visualize how different water utilities have responded to this mandate. In addition to displaying a summary of water use relative to the conservation target for each district, we also calculate the electricity savings associated with the reduced demand on water infrastructure services using estimates of average energy intensity per hydrologic region. We then convert the electricity savings into avoided greenhouse gas (GHG) emissions based on the emissions factor specific to water utility's regional electricity provider. We can view the total water, energy, and GHG savings aggregated at the state level, as well as for each of the individual water utilities. One of the significant findings is that the electricity savings associated with the observed achievements in water conservation is roughly equivalent to the total electricity savings estimated for all of the energy IOU efficiency programs for the period from July through September 2015 (the period where data was available for both initiatives). In addition, the water conservation-related GHG savings over the same period represent the equivalent of taking about 50,000 cars off the road for a year.

In addition to the water conservation data, we prepared a few summary tables of the most common water quality testing and stormwater violation data for each utility. This data demonstrates how additional data could be integrated into the application to enrich the summary reports for each utility.

### Additional Resources

- [Application: CA H2Open](https://cwee.shinyapps.io/greengov/#)
- [Source Code: https://github.com/ucd-cwee/greengov-challenge](https://github.com/ucd-cwee/greengov-challenge#)
- [Presentation: CA H2Open](http://www.waterboards.ca.gov/resources/data_databases/docs/cah2open_pres.mp4#)
- [Slides: CA H2Open](http://www.waterboards.ca.gov/resources/data_databases/docs/cah2open.pdf#)
