---
title: "Dashboard on Efficiency and Bioassessment in Water Quality Enforcement"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "Mark Tompkins"
  - "Seth Lalonde"
  - "Mike Urkov"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 Data Innovation Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

Our entry is a dashboard that demonstrates the efficiency of enforcement actions relative to stream health at the county level. The dashboard allows a user to select a contaminant (or suite of contaminants) and a county in California to chart MCL exceedances by contaminant and county. The dashboard also presents CSCI stream condition scores for the selected County and the total dollar assessment for all enforcement actions in the county. Next, the dashboard calculates the percent of “intact” stream condition in the County as the average CSCI score divided by 0.92 (the intact threshold). Finally, the dashboard calculates the cost in dollars per CSCI unit as a measure of efficiency of enforcement relative to stream condition. Try selecting multiple chemicals. Compare different counties. Explore the MCL exceedances to see which constituents are the biggest problems. Enjoy!

### Additional Resources

- [Application: Efficiency and Bioassessment in Water Quality Enforcement](https://public.tableau.com/profile/mark.tompkins#!/vizhome/DataChallengeFinal/Dashboard1)
- [Presentation: Dashboard on Efficiency and Bioassessment in Water Quality Enforcement](http://www.waterboards.ca.gov/resources/data_databases/docs/bioassesswq_pres.mp4#)
