---
title: "Demographic and Water Data Demonstration"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "Cyrus Pinto"
  - "Mike Dougherty"
  - "Joel Natividad"
  - "Sami Baig"
  - "Andrew Blythe"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 Data Innovation Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

We set out to examine how water quality information informs the demographics of the areas around it.  In particular, we considered whether the reported water quality and toxicity metrics correlate with the average income levels or ethnic makeup of a region. We examined the records from the CEDEN Water Quality and Toxicity databases from August 1st 2012-July 31st 2015.  The CEDEN data was married with the 2010 Census and income data by zip code.

Each substance or metric tested for in the dataset was tested to see how well it correlated to five variables for that particular zip code: mean income; median income; percentage of the population that is White; percentage of the population that is Hispanic; and percentage of the population that is African American.  Analytes such as Chlordane, Methoxychlor, Endrin Ketone and PBDE 140 showed very strong negative correlation with mean and median income as well as the percentage of the population that is White. Meanwhile strong positive correlations with the percentages that are Black or Hispanic. This suggests that these substances are found in higher levels in the lower income and/or predominantly Black and/or Hispanic neighborhoods.


### Additional Resources

- [Application: California Water Quality](http://www.civicdashboards.com/project/cawater#)
- [Application: Water Data With Demographics](http://catalog.civicdashboards.com/dataset/water-data-with-demographics#)
- [Presentation: Demographic and Water Data Demonstration](http://www.waterboards.ca.gov/resources/data_databases/docs/demwaterdata_pres.mp4#)
- [Slides: Demographic and Water Data Demonstration](http://www.waterboards.ca.gov/resources/data_databases/docs/demwaterdata.pdf#)
