---
title: "map.waterauditca.org"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

This web map (under active development) combines information about NID-regulated reservoirs with post-API processed data from USGS stream gauges (future features are discussed). This will allow our organization (and potentially regulators) to monitor reservoir operators' compliance with FGC 5937. The application is a web-based version of desktop software already used by the organization to advance ecological conservation efforts. Weaknesses of existing stream flow measurement infrastructure is illustrated, and the application addresses these issues by only designating gauges as a "active" if data is reported. The significance of accurate stream flow measurements to ecological conservation is discussed.
 
 This is a simple data visualization which provides insight into water resource monitoring in the State, and will be used by our organization to support decisions regarding future litigation. Future data sharing objectives are discussed, but largely concern filling information gaps identified through the application or publishing previously-unpublished public records.
 
 The datasets implemented in this Beta are the National Inventory of Dams (Army Corps of Engineers) and the USGS Instantaneous Values REST Web Service. (Datasets which informed development of this work but are not implemented include: NOAA's Essential Fish Habitat GIS Shapefiles, USGS's Hydrologic Unit Maps, the California Data Exchange Center, and the California DFG's BIOS View, among others.)

### Additional Resources

- [Slides](https://drive.google.com/open?id=0B5n4IeHrVBinSzZWV1VQUl93NXM)
- <map.waterauditca.org>
