---
title: "Stream Monitor App"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

Our project is the Stream Monitor App, which allows people to “subscribe” to specific rivers, and revive alerts when the river is forecasted to exceed a high or low-flow threshold. The app makes use of the 10 day river forecasts coming from the National Weather Service’s new National Water Model as its main data source. When users open the app, they are presented with a map of all the nation’s rivers, colored according to whether they are currently above or below their average flow for the present month. When users subscribe to a river, they can set various alert levels, and the app checks the National Water Model every hour, triggering an alert if the flow is forecasted to cross of of those levels at any point in the next ten days.
 
 This app allows concerned citizens to monitor the streams they care about, and understand the flow thresholds that define their hydrology. For example, if a user observes that a given stream has become too low for salmon to pass, they can use the app to check what flow rate corresponds to that threshold. They can check if the conditions are expected to persist or ameliorate, and set an alert so that next time the river is forecasted to drop down this low, they will receive 10 days warning. Water managers can use the app to examine forecasted water availability for withdrawals, dam operators can use it to forecast inflows and manage releases, and recreational water users can plan their next kayaking or fishing trip for when conditions are best.

### Additional Resources

- [Slides](https://drive.google.com/open?id=0B5n4IeHrVBinbEl5NHFIVUhIM0E)
