---
title: "The California Water Planning Information Exchange (Water PIE)"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "NA"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

Based on Data Basin technology, the Conservation Biology Institute (CBI) recently completed a web-based data sharing and map visualization pilot called the Water Planning Information Exchange (or Water PIE) for the California Department of Water Resources. This web mapping platform was constructed around four primary goals – improve spatial data accessibility; allow for integration of datasets from disparate places; make the system easy to use; and support various forms of collaboration. The pilot project demonstrated that the platform supports time series data; for example, reporting data from stationary locations such as groundwater well readings.
 While the platform contains several novel technical approaches to online mapping and data sharing, it’s most unique strengths pertain to features that support a variety of social interactions. Working from personal accounts, users manage content in their own private workspaces that they can return to at any time. Users can query spatial datasets, load their own datasets, build new maps from the large library of authoritative data, download content, and share content with whomever they wish. They can easily create public or private working groups to address any topic of interest and numerous platform features (e.g., commenting on maps) allow for effective collaboration.

### Additional Resources

- [Slides](https://drive.google.com/file/d/0B5n4IeHrVBinS1FyeEJkMHdaZ2c/view?resourcekey=0-YQ2WWx4xoOPwoTJXYIMr9Q)
- <https://cadwr.databasin.org/>
