---
title: "WaterBudget"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "Alex Nisnevich"
  - "Mehdi Jamei"
  - "Kirtan Upadhyaya"
  - "Everett Wetchler"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

Water is a scarce and restricted commodity and it has to be managed as such. Inspired by personal finance applications such as Mint and Level, and powered by machine learning techniques, we have created a proof-of-concept application, WaterBudget, to assist water districts to manage and plan their water usage and conservation plans. By analyzing the historical water usage patterns in each district, WaterBudget predicts total monthly and annual water usage, and compares it to the set target. The water usage prediction allows water districts to be proactive and implement necessary water conservation measures to ensure reaching the water conservation targets. In the prototype we've developed, the targets set by the State (2015) were used, however, in practice, they could be set by local administrations too. In addition to budgeting and planning purposes, this application allows the residents to easily follow their respective water suppliers' performance in water conservation.

### Additional Resources

- [Slides](https://drive.google.com/file/d/0B5n4IeHrVBinMGxtcVp0M1YtbDQ/view?resourcekey=0-fDKdS5WlG96ZJQZpvABRpA)
- <https://bayesimpact.github.io/water/>
- <https://github.com/bayesimpact/water>
