---
title: "Water Supply App"
# subtitle: 
# description: 
format: html
# title-block-categories: true
# title-block-banner: true
author: 
  - "Kylie Pace"
# author:
#   - name: 
#     url: 
#     affiliation: 
#     affiliation-url:
# abstract: ""
# abstract-title: ""
categories: 
  - "2016 White House Water Data Challenge"
  - "Honorable Mention 🏆"
date: "2016-06-30"
date-format: "YYYY"
---

<!-- COMMENT
## params_NOTUSED-proj_title

#### Year: params_NOTUSED-year

#### Topics: params_NOTUSED-topics

#### Awards: params_NOTUSED-awards

#### Team Members: params_NOTUSED-team_members
UNCOMMENT -->

### Project Description

The project title is Water Supply App. It uses a json object created from the State Water Resources Control Board's Water Rights data (http://www.waterboards.ca.gov/waterrights/water_issues/programs/ewrims/index.shtml), USGS StreamStats data, and USGS 1:1,000,000-scale streams to facilitate the creation of a water supply report. The latter two datasets are accessed via USGS APIs (streamstats and tracer). Although the base mapping service is through esri's javascript api, no services were used that required payment to them.
 
 The app combines the steps that staff in the Division of Water Rights take to create a water supply report, which is part of the water availability analysis performed for new appropriative water right proposals. The user selects the proposed point of diversion and USGS Tracer finds the downstream flowline to the Pacific Ocean. The user then selects which existing water rights near the flowline to include in the analysis. The app delineates a watershed at each existing water right diversion point and generates a table that shows two pieces of information the user would otherwise have to calculate in Excel: the area of each watershed, and the sum of all existing water right diversions within that watershed. We think this has potential to save staff significant time in calculating water supply, especially if riparian rights' statements of diversion and use could be included in the SWRCB dataset.
 
 This demo version filters water rights for active appropriative rights, but future versions could offer more filter functionality, such as the diversion season. Also, this demo is strictly a front-end project, but ideally the server would send the finished table to the user for download so that the rest of the water availability analysis can be completed.

### Additional Resources

- [Slides](https://drive.google.com/file/d/0B5n4IeHrVBinWXBxa2lCSkZ1dlk/view?resourcekey=0-oKk-NdHuG7_7FsvExBIIgg)
- <http://kyliepace.github.io/waterChallenge>
- <http://github.com/kyliepace/waterChallenge>
