project:
  type: website
  output-dir: docs

website:
  twitter-card: true
  opengraph: true
  title: "CA Water Data Challenge Project Repository"
  navbar:
    background: primary
    # logo: 'images/Data_Bear.png'
    left:
      - href: index.qmd
        text: Home
      - events.qmd
      - awards.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/CAWaterBoardDataCenter/water-data-challenge-project-repository

format:
  html:
    # theme: cosmo
    theme:
      # - default
      # - custom.scss
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    # css: styles.css
    fontsize: .95em

editor: source

